# Generated by Django 2.2 on 2020-09-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0003_auto_20200924_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('empid', models.CharField(db_index=True, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('post', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr', to='Accounts.HR', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('empid', models.CharField(db_index=True, max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('post', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty', to='Accounts.Faculty', unique=True)),
            ],
        ),
    ]
