# Generated by Django 2.2 on 2020-09-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='empid',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
