# Generated by Django 2.2 on 2020-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200923_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='empid',
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
    ]
