# Generated by Django 3.1.1 on 2020-09-30 08:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20200924_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPStore',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=8)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
